# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

###############
# Author info #
###############

author:
    # Site's author name
    # Default: not set (author name is not displayed)
    name: Your awesome name

    # Site's author email
    # Default: not set (author email is not displayed)
    email: your-email@yourdomain.com

    # Site's author website, profile
    # Default: not set (author site is not displayed)
    site: http://yourdomain.com

############
# Building #
############

# Encoding
# Set the encoding of files by name
# Default: "utf-8"
# encoding: "utf-8"

# Available encodings can be shown by the command:
# ruby -e 'puts Encoding::list.join("\n")'

# Excerpt separator
# Completely disable excerpts by setting your excerpt_separator to ""
# Default: "\n\n"
excerpt_separator: <!--more-->

# For more info on post excerpts, please refer to
# http://jekyllrb.com/docs/posts/#post-excerpts

# Exclude
# Exclude directories and/or files from the conversion. These exclusions are
# relative to the site's source directory and cannot be outside the source
# directory.
#
# The following items will not be processed, by default.
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
# Create a custom list to override the default setting.
    - LICENSE
    - README.md

# Markdown renderer
# Sets the Markdown renderer to be used by Jekyll (kramdown, redcarpet or your
# own)
# Default: kramdown
# markdown: kramdown

# For more info on how to use and configure Markdown renderers, as well as how
# to create custom renderers, please refer to
# http://jekyllrb.com/docs/configuration/#markdown-options

# Permalink
# Set the siteâ€™s URLs style
# Default: date
permalink: pretty

# For more info on permalinks, please refer to
# http://jekyllrb.com/docs/permalinks/

######################
# Google integration #
######################

google:
    # Google Analytics Property ID
    # Allows tracking site pageviews and other events using Google Analytics.
    # Default: not set (Google Analytics is not used to track site pageviews)
    # analytics_property_id: UA-12345678-9

    # If you do not know your Property ID, take a look at
    # https://support.google.com/analytics/answer/1032385

    # For more info on Google Analytic, please refer to
    # https://support.google.com/analytics/

    # Google Custom Search Engine ID
    # Allows visitors to search the website without leaving it, using a custom
    # search engine powered by Google.
    # Default: not set (instead of a CSE, Google is used to handle searching)
    # cse_id: 123456789012345678901:abcdefghijk

    # If you do not know your CSE ID, take a look at
    # https://support.google.com/customsearch/answer/2649143

    # For more info on Google Custom Search Engine, please refer to
    # https://support.google.com/customsearch/

    # Google AdSense settings
    # Allows to earn money by showing ads on the website.
    adsense:
        # Google AdSense publisher ID
        # Your publisher ID is the unique identifier for your AdSense account.
        # Default: not set (Google AdSense is not used to show ads)
        # publisher_id: ca-pub-1234567890123456

        # If you do not know your publisher ID, take a look at
        # https://support.google.com/adsense/answer/105516

        # Ad unit ID for the ad displayed at the top of the page content, bellow
        # the title, if in a page or post, or after the first post, if in a post
        # listing
        # Default: not set (no ad is displayed at the top)
        # content_ad_unit_1: 1234567890

        # Ad unit ID for the ad displayed inside the page content, randomly
        # placed between paragraphs, if in a page or post, or between posts, if
        # in a post listing
        # Default: not set (no ad is displayed in the page content)
        # content_ad_unit_2: 0987654321

        # Ad unit ID for the ad displayed in the sidebar
        # Default: not set (no ad is displayed in the sidebar)
        # sidebar_ad_unit: 1231231231

        # Note: use only responsive ad units

    # For more info on Google AdSense, please refer to
    # https://support.google.com/adsense/

##############
# Pagination #
##############

# Specifies how many items should be displayed per page
# Default: not set (pagination disabled)
# paginate: 10

# You may also specify the destination of the pagination pages
# Default: /page:num (for example, /page2, /page3, etc)
# paginate_path: "/blog/page/:num/"

# For more info on pagination, please refer to
# http://jekyllrb.com/docs/pagination/

###########
# Plugins #
###########

plugins:
    # Jekyll Feed plugin
    # https://github.com/jekyll/jekyll-feed
    # Plugin to generate an Atom (RSS-like) feed of your Jekyll posts
    - jekyll-feed

    # Default pagination generator for Jekyll
    # https://github.com/jekyll/jekyll-paginate
    - jekyll-paginate

    # Jekyll Sitemap Generator Plugin
    # https://github.com/jekyll/jekyll-sitemap
    # Plugin to silently generate a sitemaps.org compliant sitemap for your site
    - jekyll-sitemap

##############
# Publishing #
##############

# Site URL
# The base protocol and hostname for the website
# Default: not set (this variable is only necessary for external systems)
# url: "https://yourdomain.com"

# Enforce the use of HTTPS on production domain
# The hostname (does not include protocol, just the domain) for which the use of
# HTTPS should be enforced
# Default: not set (the use of HTTPS is never enforced)
# enforce_https: "yourdomain.com"

###########
# Serving #
###########

# Base URL
# Serve the website from the given base URL (does not include hostname)
# Default: "" (website is at the root of the domain)
# baseurl: ""

# For more info on the serve command options, please refer to
# http://jekyllrb.com/docs/configuration/

#################
# Site settings #
#################

# Site title
title: Your awesome title

# Site description
description: > # this means to ignore newlines until the text ends
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.

# Default site image
# Image used as a default thumbnail for pages and posts which do not have an
# thumbnail explicitly set by the front matter image variable.
# Default: not set (no image is displayed if an image is not explicitly set)
image: "/assets/favicons/android-chrome-192x192.png"

# Site language
# A language tag following the language tag syntax (IETF's BCP 47). This is
# meant to assist search engines and browsers.
# Default: not set (do not associate any language with this site's content)
lang: en

# For more info on language tags, please refer to
# http://www.w3.org/International/articles/language-tags/

# Navigation bar
# Allows to customize the links shown on the navigation bar
# Default: not set (links to all pages are shown)
# navigation:
#     -
#         title: "Link one"
#         url: "/link/one/"
#     -
#         title: "Link two"
#         url: "/link/two/"

###################
# Social networks #
###################

# AddThis profile ID
# AddThis is a content sharing platform. It can be used to better integrate the
# website with social networks. An AddThis profile contains configuration options
# and analytics data for a website.
# Default: not set (AddThis is not used to handle social networks integration)
# addthis_profile_id: "ra-example123456789"

# If you do not know your AddThis profile ID, you can find it at
# https://www.addthis.com/settings/publisher

# For more info on AddThis, please refer to
# http://support.addthis.com/

# Disqus shortname
# Disqus is a blog comment hosting service for websites. A Disqus shortname is
# the unique identifier assigned to a Disqus site. All the comments posted to a
# site are referenced with the shortname. The shortname tells Disqus to load
# only your site's comments, as well as the settings specified in your Disqus
# admin.
# Default: not set (do not use Disqus to handle comments)
# disqus_shortname: "my_disqus_shortname"

# If you do not know your Disqus shortname, take a look at
# https://help.disqus.com/customer/portal/articles/466208

# For more info on Disqus, please refer to
# https://help.disqus.com/

facebook:
    # Facebook Application ID
    # You may associate your site with a Facebook App so you can measure your
    # site's performance on Facebook using Facebook Insights. After the App is
    # created, inform the Facebook App ID here.
    # Default: not set (the site is not bound to any Facebook App)
    # app_id: 123456789012345

    # For more info on Facebook Insights, please refer to
    # https://developers.facebook.com/docs/platforminsights/domains

    # Facebook Page ID
    # If your site has a corresponding Facebook Page, inform its ID here
    # Example: 123456, if your page is at https://facebook.com/Page-Name/123456
    # page_id: 1234567890123456

    # For more info on Facebook Pages, please refer to
    # https://www.facebook.com/about/pages

    # Facebook username
    # Examples:
    # username, if your profile is at https://facebook.com/username or
    # Page-Name/123456, if your page is at https://facebook.com/Page-Name/123456
    # Default: not set (Facebook URL is not displayed)
    # username: "username"

# Foursquare username
# Example: username, if your Foursquare URL is https://foursquare.com/username
# Default: not set (Foursquare URL is not displayed)
# foursquare_username: "username"

# GitHub username
# Example: jekyll, if your GitHub URL is https://github.com/jekyll
# Default: not set (GitHub URL is not displayed)
github_username: "jekyll"

# Google Plus user ID
# Example: 123456789098765432123, if your Google Plus URL is
# https://plus.google.com/123456789098765432123
# Default: not set (Google Plus URL is not displayed)
# google_plus_user_id: 123456789098765432123

# LinkedIn username
# Example: username, if your LinkedIn public profile URL is
# https://www.linkedin.com/in/username
# Default: not set (LinkedIn public profile URL is not displayed)
# linkedin_username: "username"

# Twitter username
# Example: jekyllrb, if your Twitter URL is https://twitter.com/jekyllrb
# Default: not set (Twitter URL is not displayed)
twitter_username: "jekyllrb"

youtube:
    # What kind of YouTube profile you have (it can be "user" or "channel")
    # Default: not set (YouTube URL is not displayed)
    # profile: "user"

    # YouTube user or channel name
    # Examples:
    # username, if your YouTube personal profile is at
    # https://www.youtube.com/user/username or
    # channelname, if your YouTube channel is at
    # https://www.youtube.com/channel/channelname
    # Default: not set (YouTube URL is not displayed)
    # name: "username"

#####################
# YAML Front Matter #
#####################

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            # Allows one to use {{ page.is_post }} to check whether the page is
            # a post, as seen on http://stackoverflow.com/a/23555679/1657502
            is_post: true

# For more info on YAML Front Matter and its configuration, please refer to
# https://jekyllrb.com/docs/frontmatter/
# https://jekyllrb.com/docs/configuration/#front-matter-defaults
